### ISSUE TITLE
Tenant Registration stopped working (/reg times out) 

### ISSUE THREAD

**Issue by alexephesoft** [aws-quickstart/saas-identity-cognito#14]
After successful installation and one week of working according to spec the Registration part of the system (/reg) stopped working by getting the time-out error. All other end-points and URLs are working fine including green light by the Tenant Registration Service Health Check. Currently, there is no way to register new tenant and everything short of complete re-installation failed to fix this issue. 

Additional Information: When I enabled detailed logging I got the following error in the log:

22:54:58
(833af352-4812-11e8-a58b-ef3f6917d35b) Sending request to http://Ephes-LoadB-6XBYF9101D8-1836787935.us-west-2.elb.amazonaws.com/user/reg
22:54:58
(833af352-4812-11e8-a58b-ef3f6917d35b) Received response. Integration latency: 99 ms
**22:54:58
(833af352-4812-11e8-a58b-ef3f6917d35b) Endpoint response body before transformations: Error provisioning tenant admin user**
22:54:58
(833af352-4812-11e8-a58b-ef3f6917d35b) Endpoint response headers: {Access-Control-Allow-Origin=*, ETag=W/"24-XvReFVeM8dbFvhcbtQuCBMtdc6I", Access-Control-Allow-Methods=GET, POST, OPTIONS, PUT, PATCH, DELETE, Connection=keep-alive, Content-Length=36, Date=Tue, 24 Apr 2018 22:54:58 GMT, Access-Control-Allow-Headers=Content-Type, Origin, X-Amz-Date, Authorization, X-Api-Key, X-Amz-Security-Token, Acc
22:54:58
(833af352-4812-11e8-a58b-ef3f6917d35b) Method response body after transformations: Error provisioning tenant admin user
22:54:58
(833af352-4812-11e8-a58b-ef3f6917d35b) Method response headers: {Access-Control-Allow-Origin=*, ETag=W/"24-XvReFVeM8dbFvhcbtQuCBMtdc6I", Access-Control-Allow-Methods=GET, POST, OPTIONS, PUT, PATCH, DELETE, Connection=keep-alive, Content-Length=36, Date=Tue, 24 Apr 2018 22:54:58 GMT, Access-Control-Allow-Headers=Content-Type, Origin, X-Amz-Date, Authorization, X-Api-Key, X-Amz-Security-Token, Acces
22:54:58
(833af352-4812-11e8-a58b-ef3f6917d35b) Successfully completed execution
22:54:58
(833af352-4812-11e8-a58b-ef3f6917d35b) **Method completed with status: 400**

**Comment by alexephesoft** [comment]
Below is the combined log from 4 different blocks of CloudWatch data. 

2018-04-27 20:57:24

(963e01e4-4a5d-11e8-a7f8-73d5adbd0647) Verifying Usage Plan for request: 963e01e4-4a5d-11e8-a7f8-73d5adbd0647. API Key: API Stage: 2ayo5w0voh/prod
(963e01e4-4a5d-11e8-a7f8-73d5adbd0647) API Key authorized because method 'OPTIONS /reg' does not require API Key. Request will not contribute to throttle or quota limits
(963e01e4-4a5d-11e8-a7f8-73d5adbd0647) Usage Plan check succeeded for API Key and API Stage 2ayo5w0voh/prod
(963e01e4-4a5d-11e8-a7f8-73d5adbd0647) Starting execution for request: 963e01e4-4a5d-11e8-a7f8-73d5adbd0647
(963e01e4-4a5d-11e8-a7f8-73d5adbd0647) HTTP Method: OPTIONS, Resource Path: /ui/reg
(963e01e4-4a5d-11e8-a7f8-73d5adbd0647) Method request path:
{}
(963e01e4-4a5d-11e8-a7f8-73d5adbd0647) Method request query string:
{}
(963e01e4-4a5d-11e8-a7f8-73d5adbd0647) Method request headers: {Accept=*/*, CloudFront-Viewer-Country=US, CloudFront-Forwarded-Proto=https, CloudFront-Is-Tablet-Viewer=false, origin=http://ephesoft-saas-identity-with-cognito-ide-webbucket-1qy768wnhyw69.s3-website-us-west-2.amazonaws.com, CloudFront-Is-Mobile-Viewer=false, User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36, X-Forwarded-Proto=https, CloudFront-Is-SmartTV-Viewer=false, Host=api.ephesoftcloud.com, Accept-Encoding=gzip, deflate, br, access-control-request-method=POST, X-Forwarded-Port=443, X-Amzn-Trace-Id=Root=1-5ae38eb4-f85154f5abee7089a7251914, Via=2.0 ee8b5e6013d73b1439e0c010462ded31.cloudfront.net (CloudFront), access-control-request-headers=content-type, X-Amz-Cf-Id=WIjDBDYi-C_YwjPwVzzCHGLF7At5VcVxZ2Ts1f29L-XtBVQ6ghGGmg==, X-Forwarded-For=142.129.173.247, 216.137.44.124, Accept-Language=en-US,en;q=0.9,ru;q=0.8, CloudFront-Is-Desktop-Viewer=true}
(963e01e4-4a5d-11e8-a7f8-73d5adbd0647) Method request body before transformations:
(963e01e4-4a5d-11e8-a7f8-73d5adbd0647) Received response. Integration latency: 0 ms
(963e01e4-4a5d-11e8-a7f8-73d5adbd0647) Endpoint response body before transformations:
(963e01e4-4a5d-11e8-a7f8-73d5adbd0647) Endpoint response headers:
{}
(963e01e4-4a5d-11e8-a7f8-73d5adbd0647) Method response body after transformations:
(963e01e4-4a5d-11e8-a7f8-73d5adbd0647) Method response headers: {Access-Control-Allow-Origin=*, Access-Control-Allow-Methods=POST,OPTIONS, Access-Control-Allow-Headers=Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token, Content-Type=application/json}
(963e01e4-4a5d-11e8-a7f8-73d5adbd0647) Successfully completed execution
(963e01e4-4a5d-11e8-a7f8-73d5adbd0647) Method completed with status: 200

2018-04-27 20:57:24

(9651d7dc-4a5d-11e8-8dbb-c5e586da8ff6) Verifying Usage Plan for request: 9651d7dc-4a5d-11e8-8dbb-c5e586da8ff6. API Key: API Stage: 2ayo5w0voh/prod
(9651d7dc-4a5d-11e8-8dbb-c5e586da8ff6) API Key authorized because method 'GET /user/pool/{id}' does not require API Key. Request will not contribute to throttle or quota limits
(9651d7dc-4a5d-11e8-8dbb-c5e586da8ff6) Usage Plan check succeeded for API Key and API Stage 2ayo5w0voh/prod
(9651d7dc-4a5d-11e8-8dbb-c5e586da8ff6) Starting execution for request: 9651d7dc-4a5d-11e8-8dbb-c5e586da8ff6
(9651d7dc-4a5d-11e8-8dbb-c5e586da8ff6) HTTP Method: GET, Resource Path: /user/pool/ccccccccc@gmain.com
(9651d7dc-4a5d-11e8-8dbb-c5e586da8ff6) Method request path: {id=ccccccccc@gmain.com}
(9651d7dc-4a5d-11e8-8dbb-c5e586da8ff6) Method request query string:
{}
(9651d7dc-4a5d-11e8-8dbb-c5e586da8ff6) Method request headers: {Accept=application/json, CloudFront-Viewer-Country=US, CloudFront-Forwarded-Proto=https, CloudFront-Is-Tablet-Viewer=false, CloudFront-Is-Mobile-Viewer=false, X-Forwarded-Proto=https, CloudFront-Is-SmartTV-Viewer=false, Host=2ayo5w0voh.execute-api.us-west-2.amazonaws.com, X-Forwarded-Port=443, X-Amzn-Trace-Id=Root=1-5ae38eb4-887b60c9c3aa68c7739a4ec0, Via=1.1 8ddadd1ab84a7f1bef108d6a72eccf06.cloudfront.net (CloudFront), X-Amz-Cf-Id=v_RXaAy-oNhdv-IU-_yyetYG3S2QIdBASMunodgMF9h7OnUw7RaP8g==, X-Forwarded-For=34.217.190.147, 52.46.17.94, content-type=application/json, CloudFront-Is-Desktop-Viewer=true}
(9651d7dc-4a5d-11e8-8dbb-c5e586da8ff6) Method request body before transformations:
(9651d7dc-4a5d-11e8-8dbb-c5e586da8ff6) Endpoint request URI: http://Ephes-LoadB-6XBYF9101D8-1836787935.us-west-2.elb.amazonaws.com/user/pool/ccccccccc@gmain.com
(9651d7dc-4a5d-11e8-8dbb-c5e586da8ff6) Endpoint request headers: {x-amzn-apigateway-api-id=2ayo5w0voh, Accept=application/json, CloudFront-Viewer-Country=US, CloudFront-Forwarded-Proto=https, CloudFront-Is-Tablet-Viewer=false, User-Agent=AmazonAPIGateway_2ayo5w0voh, CloudFront-Is-Mobile-Viewer=false, X-Forwarded-Proto=https, CloudFront-Is-SmartTV-Viewer=false, X-Forwarded-Port=443, X-Amzn-Trace-Id=Root=1-5ae38eb4-887b60c9c3aa68c7739a4ec0, Via=1.1 8ddadd1ab84a7f1bef108d6a72eccf06.cloudfront.net (CloudFront), X-Amz-Cf-Id=v_RXaAy-oNhdv-IU-_yyetYG3S2QIdBASMunodgMF9h7OnUw7RaP8g==, X-Forwarded-For=34.217.190.147, 52.46.17.94, content-type=application/json, CloudFront-Is-Desktop-Viewer=true}
(9651d7dc-4a5d-11e8-8dbb-c5e586da8ff6) Endpoint request body after transformations:
(9651d7dc-4a5d-11e8-8dbb-c5e586da8ff6) Sending request to http://Ephes-LoadB-6XBYF9101D8-1836787935.us-west-2.elb.amazonaws.com/user/pool/ccccccccc@gmain.com
(9651d7dc-4a5d-11e8-8dbb-c5e586da8ff6) Received response. Integration latency: 62 ms
(9651d7dc-4a5d-11e8-8dbb-c5e586da8ff6) Endpoint response body before transformations:
{
    "Error": "Error getting user"
}
(9651d7dc-4a5d-11e8-8dbb-c5e586da8ff6) Endpoint response headers: {Access-Control-Allow-Origin=*, ETag=W/"20-ZVwZNOPQ6UrcJJWm5ZBjvZt9bWc", Access-Control-Allow-Methods=GET, POST, OPTIONS, PUT, PATCH, DELETE, Connection=keep-alive, Content-Length=32, Date=Fri, 27 Apr 2018 20:57:24 GMT, Access-Control-Allow-Headers=Content-Type, Origin, X-Amz-Date, Authorization, X-Api-Key, X-Amz-Security-Token, Access-Control-Allow-Headers, X-Requested-With, Access-Control-Allow-Origin, Content-Type=text/html; charset=utf-8, X-Powered-By=Express}
(9651d7dc-4a5d-11e8-8dbb-c5e586da8ff6) Method response body after transformations:
{
    "Error": "Error getting user"
}
(9651d7dc-4a5d-11e8-8dbb-c5e586da8ff6) Method response headers: {Access-Control-Allow-Origin=*, ETag=W/"20-ZVwZNOPQ6UrcJJWm5ZBjvZt9bWc", Access-Control-Allow-Methods=GET, POST, OPTIONS, PUT, PATCH, DELETE, Connection=keep-alive, Content-Length=32, Date=Fri, 27 Apr 2018 20:57:24 GMT, Access-Control-Allow-Headers=Content-Type, Origin, X-Amz-Date, Authorization, X-Api-Key, X-Amz-Security-Token, Access-Control-Allow-Headers, X-Requested-With, Access-Control-Allow-Origin, Content-Type=text/html; charset=utf-8, X-Powered-By=Express}
(9651d7dc-4a5d-11e8-8dbb-c5e586da8ff6) Successfully completed execution
(9651d7dc-4a5d-11e8-8dbb-c5e586da8ff6) Method completed with status: 400

2018-04-27 20:57:25

(966252a9-4a5d-11e8-a448-ffa8ff53cc2d) Verifying Usage Plan for request: 966252a9-4a5d-11e8-a448-ffa8ff53cc2d. API Key: API Stage: 2ayo5w0voh/prod
(966252a9-4a5d-11e8-a448-ffa8ff53cc2d) API Key authorized because method 'POST /user/reg' does not require API Key. Request will not contribute to throttle or quota limits
(966252a9-4a5d-11e8-a448-ffa8ff53cc2d) Usage Plan check succeeded for API Key and API Stage 2ayo5w0voh/prod
(966252a9-4a5d-11e8-a448-ffa8ff53cc2d) Starting execution for request: 966252a9-4a5d-11e8-a448-ffa8ff53cc2d
(966252a9-4a5d-11e8-a448-ffa8ff53cc2d) HTTP Method: POST, Resource Path: /user/reg
(966252a9-4a5d-11e8-a448-ffa8ff53cc2d) Method request path:
{}
(966252a9-4a5d-11e8-a448-ffa8ff53cc2d) Method request query string:
{}
(966252a9-4a5d-11e8-a448-ffa8ff53cc2d) Method request headers: {Accept=application/json, CloudFront-Viewer-Country=US, CloudFront-Forwarded-Proto=https, CloudFront-Is-Tablet-Viewer=false, CloudFront-Is-Mobile-Viewer=false, X-Forwarded-Proto=https, CloudFront-Is-SmartTV-Viewer=false, Host=2ayo5w0voh.execute-api.us-west-2.amazonaws.com, X-Forwarded-Port=443, X-Amzn-Trace-Id=Root=1-5ae38eb5-1fd8169fff01ec7a8a934456, Via=1.1 2d8af5cc5befc5d35bb54b4a5b6494c9.cloudfront.net (CloudFront), X-Amz-Cf-Id=nFw6aBeY0xd6ekDtpOclJ4U0hfljnA7H2O9OtBWyr9Nw2RJs-TGD6w==, X-Forwarded-For=34.217.190.147, 52.46.17.81, content-type=application/json, CloudFront-Is-Desktop-Viewer=true}
(966252a9-4a5d-11e8-a448-ffa8ff53cc2d) Method request body before transformations:
{
    "tenant_id": "TENANTd0c86e0dcfb740a4a1eef1a27669ebf2",
    "companyName": "ddddddddd",
    "accountName": "ddddddddd",
    "ownerName": "ccccccccc@gmain.com",
    "email": "ccccccccc@gmain.com",
    "userName": "ccccccccc@gmain.com",
    "firstName": "aaaaaaaaaaaaaaaa",
    "lastName": "bbbbbbbbbbbbbbbbb"
}
(966252a9-4a5d-11e8-a448-ffa8ff53cc2d) Endpoint request URI: http://Ephes-LoadB-6XBYF9101D8-1836787935.us-west-2.elb.amazonaws.com/user/reg
(966252a9-4a5d-11e8-a448-ffa8ff53cc2d) Endpoint request headers: {x-amzn-apigateway-api-id=2ayo5w0voh, Accept=application/json, CloudFront-Viewer-Country=US, CloudFront-Forwarded-Proto=https, CloudFront-Is-Tablet-Viewer=false, User-Agent=AmazonAPIGateway_2ayo5w0voh, CloudFront-Is-Mobile-Viewer=false, X-Forwarded-Proto=https, CloudFront-Is-SmartTV-Viewer=false, X-Forwarded-Port=443, X-Amzn-Trace-Id=Root=1-5ae38eb5-1fd8169fff01ec7a8a934456, Via=1.1 2d8af5cc5befc5d35bb54b4a5b6494c9.cloudfront.net (CloudFront), X-Amz-Cf-Id=nFw6aBeY0xd6ekDtpOclJ4U0hfljnA7H2O9OtBWyr9Nw2RJs-TGD6w==, X-Forwarded-For=34.217.190.147, 52.46.17.81, content-type=application/json, CloudFront-Is-Desktop-Viewer=true}
(966252a9-4a5d-11e8-a448-ffa8ff53cc2d) Endpoint request body after transformations:
{
    "tenant_id": "TENANTd0c86e0dcfb740a4a1eef1a27669ebf2",
    "companyName": "ddddddddd",
    "accountName": "ddddddddd",
    "ownerName": "ccccccccc@gmain.com",
    "email": "ccccccccc@gmain.com",
    "userName": "ccccccccc@gmain.com",
    "firstName": "aaaaaaaaaaaaaaaa",
    "lastName": "bbbbbbbbbbbbbbbbb"
}
(966252a9-4a5d-11e8-a448-ffa8ff53cc2d) Sending request to http://Ephes-LoadB-6XBYF9101D8-1836787935.us-west-2.elb.amazonaws.com/user/reg
(966252a9-4a5d-11e8-a448-ffa8ff53cc2d) Received response. Integration latency: 170 ms
(966252a9-4a5d-11e8-a448-ffa8ff53cc2d) Endpoint response body before transformations: Error provisioning tenant admin user
(966252a9-4a5d-11e8-a448-ffa8ff53cc2d) Endpoint response headers: {Access-Control-Allow-Origin=*, ETag=W/"24-XvReFVeM8dbFvhcbtQuCBMtdc6I", Access-Control-Allow-Methods=GET, POST, OPTIONS, PUT, PATCH, DELETE, Connection=keep-alive, Content-Length=36, Date=Fri, 27 Apr 2018 20:57:25 GMT, Access-Control-Allow-Headers=Content-Type, Origin, X-Amz-Date, Authorization, X-Api-Key, X-Amz-Security-Token, Access-Control-Allow-Headers, X-Requested-With, Access-Control-Allow-Origin, Content-Type=text/html; charset=utf-8, X-Powered-By=Express}
(966252a9-4a5d-11e8-a448-ffa8ff53cc2d) Method response body after transformations: Error provisioning tenant admin user
(966252a9-4a5d-11e8-a448-ffa8ff53cc2d) Method response headers: {Access-Control-Allow-Origin=*, ETag=W/"24-XvReFVeM8dbFvhcbtQuCBMtdc6I", Access-Control-Allow-Methods=GET, POST, OPTIONS, PUT, PATCH, DELETE, Connection=keep-alive, Content-Length=36, Date=Fri, 27 Apr 2018 20:57:25 GMT, Access-Control-Allow-Headers=Content-Type, Origin, X-Amz-Date, Authorization, X-Api-Key, X-Amz-Security-Token, Access-Control-Allow-Headers, X-Requested-With, Access-Control-Allow-Origin, Content-Type=text/html; charset=utf-8, X-Powered-By=Express}
(966252a9-4a5d-11e8-a448-ffa8ff53cc2d) Successfully completed execution
(966252a9-4a5d-11e8-a448-ffa8ff53cc2d) Method completed with status: 400

2018-04-27 20:57:24

(964777af-4a5d-11e8-9bef-212cd9bdbcd7) Verifying Usage Plan for request: 964777af-4a5d-11e8-9bef-212cd9bdbcd7. API Key: API Stage: 2ayo5w0voh/prod
(964777af-4a5d-11e8-9bef-212cd9bdbcd7) API Key authorized because method 'POST /reg' does not require API Key. Request will not contribute to throttle or quota limits
(964777af-4a5d-11e8-9bef-212cd9bdbcd7) Usage Plan check succeeded for API Key and API Stage 2ayo5w0voh/prod
(964777af-4a5d-11e8-9bef-212cd9bdbcd7) Starting execution for request: 964777af-4a5d-11e8-9bef-212cd9bdbcd7
(964777af-4a5d-11e8-9bef-212cd9bdbcd7) HTTP Method: POST, Resource Path: /ui/reg
(964777af-4a5d-11e8-9bef-212cd9bdbcd7) Method request path:
{}
(964777af-4a5d-11e8-9bef-212cd9bdbcd7) Method request query string:
{}
(964777af-4a5d-11e8-9bef-212cd9bdbcd7) Method request headers: {Accept=application/json, text/plain, */*, CloudFront-Viewer-Country=US, CloudFront-Forwarded-Proto=https, CloudFront-Is-Tablet-Viewer=false, origin=http://ephesoft-saas-identity-with-cognito-ide-webbucket-1qy768wnhyw69.s3-website-us-west-2.amazonaws.com, CloudFront-Is-Mobile-Viewer=false, Referer=http://ephesoft-saas-identity-with-cognito-ide-webbucket-1qy768wnhyw69.s3-website-us-west-2.amazonaws.com/, User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36, X-Forwarded-Proto=https, CloudFront-Is-SmartTV-Viewer=false, Host=api.ephesoftcloud.com, Accept-Encoding=gzip, deflate, br, X-Forwarded-Port=443, X-Amzn-Trace-Id=Root=1-5ae38eb4-7755c160df129de057b599dc, Via=2.0 ee8b5e6013d73b1439e0c010462ded31.cloudfront.net (CloudFront), X-Amz-Cf-Id=kjEQUTUaBVXlhYrhyhB2DLNBySeNuwH6ntKyBU-APR0fWjgYD4WU9w==, X-Forwarded-For=142.129.173.247, 216.137.44.120, content-type=application/json;charset=UTF-8, Accept-Language=en-US,en;q= [TRUNCATED]
(964777af-4a5d-11e8-9bef-212cd9bdbcd7) Method request body before transformations:
{
    "id": "",
    "companyName": "ddddddddd",
    "accountName": "ddddddddd",
    "ownerName": "ccccccccc@gmain.com",
    "email": "ccccccccc@gmain.com",
    "userName": "ccccccccc@gmain.com",
    "firstName": "aaaaaaaaaaaaaaaa",
    "lastName": "bbbbbbbbbbbbbbbbb"
}
(964777af-4a5d-11e8-9bef-212cd9bdbcd7) Endpoint request URI: http://Ephes-LoadB-6XBYF9101D8-1836787935.us-west-2.elb.amazonaws.com/reg
(964777af-4a5d-11e8-9bef-212cd9bdbcd7) Endpoint request headers: {x-amzn-apigateway-api-id=2ayo5w0voh, Accept=application/json, text/plain, */*, CloudFront-Viewer-Country=US, CloudFront-Forwarded-Proto=https, CloudFront-Is-Tablet-Viewer=false, origin=http://ephesoft-saas-identity-with-cognito-ide-webbucket-1qy768wnhyw69.s3-website-us-west-2.amazonaws.com, User-Agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36, CloudFront-Is-Mobile-Viewer=false, Referer=http://ephesoft-saas-identity-with-cognito-ide-webbucket-1qy768wnhyw69.s3-website-us-west-2.amazonaws.com/, X-Forwarded-Proto=https, CloudFront-Is-SmartTV-Viewer=false, Accept-Encoding=gzip, deflate, br, X-Forwarded-Port=443, X-Amzn-Trace-Id=Root=1-5ae38eb4-7755c160df129de057b599dc, Via=2.0 ee8b5e6013d73b1439e0c010462ded31.cloudfront.net (CloudFront), X-Amz-Cf-Id=kjEQUTUaBVXlhYrhyhB2DLNBySeNuwH6ntKyBU-APR0fWjgYD4WU9w==, X-Forwarded-For=142.129.173.247, 216.137.44.120, content-type=application/json;charset=UTF-8, Accept-Language= [TRUNCATED]
(964777af-4a5d-11e8-9bef-212cd9bdbcd7) Endpoint request body after transformations:
{
    "id": "",
    "companyName": "ddddddddd",
    "accountName": "ddddddddd",
    "ownerName": "ccccccccc@gmain.com",
    "email": "ccccccccc@gmain.com",
    "userName": "ccccccccc@gmain.com",
    "firstName": "aaaaaaaaaaaaaaaa",
    "lastName": "bbbbbbbbbbbbbbbbb"
}
(964777af-4a5d-11e8-9bef-212cd9bdbcd7) Sending request to http://Ephes-LoadB-6XBYF9101D8-1836787935.us-west-2.elb.amazonaws.com/reg

2018-04-27 20:57:53

(964777af-4a5d-11e8-9bef-212cd9bdbcd7) Execution failed due to a timeout error
(964777af-4a5d-11e8-9bef-212cd9bdbcd7) Gateway response type: DEFAULT_5XX with status code: 504
(964777af-4a5d-11e8-9bef-212cd9bdbcd7) Gateway response body:
{
    "message": "Endpoint request timed out"
}
(964777af-4a5d-11e8-9bef-212cd9bdbcd7) Gateway response headers: {Access-Control-Allow-Origin=*, Access-Control-Allow-Methods=POST,OPTIONS, Access-Control-Allow-Headers=Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token}
(964777af-4a5d-11e8-9bef-212cd9bdbcd7) Method completed with status: 504

**Comment by alexephesoft** [comment]
Here is the service (Registration Service) log:

2018-04-26 00:47:07
Tenant Registration Manager service started on port 3004
WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
debug: Creating Tenant ID: TENANT577dca79-f4b9-4c22-9e5d-9f7f4ac6c9fc
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'message' of null
(node:1) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
debug: Creating Tenant ID: TENANT3add5308-94d7-48f3-8810-1888292ddacf
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'message' of null
debug: Creating Tenant ID: TENANT852c12dd-e166-4899-b077-f3b442fdf482
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: Cannot read property 'message' of null
debug: Creating Tenant ID: TENANTf7147279-5daf-4b7a-b552-37181a207f6d
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): TypeError: Cannot read property 'message' of null
debug: Creating Tenant ID: TENANT7da775a1-ff1c-4478-8005-4311e420d808
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): TypeError: Cannot read property 'message' of null
debug: Creating Tenant ID: TENANT99e04316-b7b0-41a7-8ca4-01ad29a612e5
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): TypeError: Cannot read property 'message' of null
debug: Creating Tenant ID: TENANT5b4e3e40-2c62-4f60-a0b1-35fbb710c104
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 7): TypeError: Cannot read property 'message' of null
debug: Creating Tenant ID: TENANT5d4a2473-a516-4042-9f06-ae1d327f975b
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 8): TypeError: Cannot read property 'message' of null
debug: Creating Tenant ID: TENANTe734aae1-47f0-4aca-a5ff-c81df835e182
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 9): TypeError: Cannot read property 'message' of null
debug: Creating Tenant ID: TENANT67dafeea-2ff6-4ed7-a442-8af0a3ca300a
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 10): TypeError: Cannot read property 'message' of null
debug: Creating Tenant ID: TENANTbc8e511e-a025-4299-9798-08fc1f9b7cea
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 11): TypeError: Cannot read property 'message' of null
debug: Creating Tenant ID: TENANT53ea3428-a924-4634-b128-cd72b7e214c3
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 12): TypeError: Cannot read property 'message' of null
debug: Creating Tenant ID: TENANT694adaf1-d6d5-4d04-9c29-e926497c8c90
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 13): TypeError: Cannot read property 'message' of null
debug: Creating Tenant ID: TENANT127bee3b-aeec-47f7-a49f-c70a0c12f393
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 14): TypeError: Cannot read property 'message' of null
debug: Creating Tenant ID: TENANT307f9459-ba0b-46b7-bae9-f69b46f1c676
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 15): TypeError: Cannot read property 'message' of null
debug: Creating Tenant ID: TENANTb5cfc28c-8138-4dd7-861a-62b2d4ce59b9
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 16): TypeError: Cannot read property 'message' of null
debug: Creating Tenant ID: TENANT51abce6c-4678-4908-b29a-a1b42f2d514d
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 17): TypeError: Cannot read property 'message' of null
debug: Creating Tenant ID: TENANT821a3f53-197f-4e0b-8f50-dfbd40534867
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 18): TypeError: Cannot read property 'message' of null
debug: Creating Tenant ID: TENANT3917577c-da4b-44a9-bae5-9a3cf15fb027
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 19): TypeError: Cannot read property 'message' of null
debug: Creating Tenant ID: TENANT700d6dc5-b03e-4cf5-b0be-ba213017449d
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 20): TypeError: Cannot read property 'message' of null
debug: Creating Tenant ID: TENANT3f103d13-6e55-4e83-930c-b49a12a370aa
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 21): TypeError: Cannot read property 'message' of null
debug: Creating Tenant ID: TENANT2f0c2ea9-dfa2-46eb-aec4-01a789471583
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 22): TypeError: Cannot read property 'message' of null
debug: Creating Tenant ID: TENANTdf777214-90f7-414b-a6a4-14dba78bb441
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 23): TypeError: Cannot read property 'message' of null
2018-04-27
debug: Creating Tenant ID: TENANTce7dbc63-b61e-4455-8a2c-718220fd002c
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 24): TypeError: Cannot read property 'message' of null
debug: Creating Tenant ID: TENANT6f6e05da-0e33-43e0-805a-04dcce9202aa
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 25): TypeError: Cannot read property 'message' of null
debug: Creating Tenant ID: TENANTb6803f7d-36dc-45c3-bc38-4340da13e463
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 26): TypeError: Cannot read property 'message' of null
debug: Creating Tenant ID: TENANTd0c86e0d-cfb7-40a4-a1ee-f1a27669ebf2
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 27): TypeError: Cannot read property 'message' of null

**Comment by judahb** [comment]
Can you get me the user manager, tenant manager, tenant registration logs. These three are reaching out to one another to register the tenant. I imagine the error is in user manager.

**Comment by alexephesoft** [comment]
Thank you, @judahb - you pointed me in the right direction. The clue to the issue was in the Tenant Log: I somehow, ran into the Max Tenant Count limitation (60 tenants). Once I deleted some unused teanats - everything started working again. Thank you!

**Comment by judahb** [comment]
@alexephesoft You can submit a service request to AWS support to increase that 60 User Pool limit if this is a production workload. Include justification when submitting the request.

**Comment by alexephesoft** [comment]
Thank you so much, @judahb! I have already submitted and received increase of the User Pool limit.
Really appreciate all your help!
