### ISSUE TITLE
How can I customize the confirmation email message for the first user of the new Tenant?

### ISSUE THREAD

**Issue by alexephesoft** [aws-quickstart/saas-identity-cognito#15]
The registration screen allows me to create a new Tenant (User Pool) and simultaneously - a new User admin of this tenant. As a confirmation, the Cognito sends a confirmation email to the user. How can I customize this Email to include my Logo and my text in the body of the email? 

I can do this after Tenant is created via AWS Console/ Comman line - but it is already late for the first user since s/he already received confirmation using the default text and Amazon Logo.

**Comment by judahb** [comment]
Hello, 
In the link below, you will see the invite message is injected via my application code when a new tenant is generated. If you wanted to change the logo and text, you can address by changing this line. Note, if this needs to be different look and feel per tenant you would need to create custom code in my micro-service to do this. 

https://github.com/aws-quickstart/saas-identity-cognito/blob/master/app/source/user-manager/src/cognito-user.js#L164

**Comment by alexephesoft** [comment]
Thank you so much! This is exactly what I was looking for!
