### ISSUE TITLE
Forgot my password feature

### ISSUE THREAD

**Issue by alexephesoft** [aws-quickstart/saas-identity-cognito#16]
How would I go about implementing this feature (Forgot my password) . Should I tap into the code that replaces temporary password with the permanent one or it is a separate new logic?

**Comment by judahb** [comment]
https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityServiceProvider.html#adminResetUserPassword-property

You need to add this in user manager microservice and add functionality in the AngularJS Client

**Comment by judahb** [comment]
@alexephesoft It sounds like you are doing a lot of work with this. I would like to get your feedback in general and understand what you are building.

**Comment by judahb** [comment]
More prescriptively, add this code to cognito-user.js 

/**
 * Reset a user password for Cognito User Pool
 * @param userPoolId The user pool where the user resides
 * @param region The aws region
 * @param userId The userId
 * @returns {Promise} Results of the deletion
 */
module.exports.adminResetUserPassword = function (userPoolId, region, userId) {
    var promise = new Promise(function(resolve, reject) {
        // init the identity provider
        var cognitoIdentityServiceProvider = new AWS.CognitoIdentityServiceProvider({
            apiVersion: '2016-04-18',
            region: configuration.aws_region
        });

        var params = {
            UserPoolId: userPoolId, /* required */
            Username: userId /* required */
        };
        // call Cognito to delete the user
        cognitoIdentityServiceProvider.adminResetUserPassword(params, function (err, data) {
            if (err)
                reject(err);
            else
                resolve(data);
        });
    });

**Comment by judahb** [comment]
Add this to the microservice

`/**
 * Reset a users password
 */
app.get('/user/password/:id', function (req, res) {
    winston.debug('Looking up user pool data for: ' + req.params.id);
    tokenManager.getSystemCredentials(function (credentials) {
        lookupUserPoolData(credentials, req.params.id, null, true, function (err, user) {
            if (err) {
                res.status(400).send('{"Error" : "Error getting user"}');
            }
            else {
                if (user.length == 0)
                    res.status(400).send('{"Error": "User not found"}');
                else {
                    // update user data
                    cognitoUsers.adminResetUserPassword(credentials, user, userPoolId, configuration.aws_region)
                        .then(function(data) {
                            res.status(200).send(data);
                        })
                        .catch(function(err) {
                            res.status(400).send("Error updating user: " + err.message);
                        });
                }
            }
        });
    });
});
`

**Comment by judahb** [comment]
Note, i still need to test these but will add in a revision in the future. Also you need to update the AngularJS client and API Gateway which i cannot do now

**Comment by alexephesoft** [comment]
Thank you so much, @judahb! Angular and Gateway API is the easiest part!

To answer your question about what we are building:  
We are developing the Multi-Tenant System in the document processing field and are currently working with AWS rep. (Miguel) as a liaison to Amazon. I would be happy to discuss the details of the design with you on a conf. call via Miguel and provide you with the all the feedback you are looking for.

**Comment by judahb** [comment]
@alexephesoft  My pleasure. Yes, Please coordinate a call through Miguel. He can find me inside Amazon.
