### ISSUE TITLE
As an order manager user when I make a request to the GET /tenants endpoint it causes the service to error with 503

### ISSUE THREAD

**Issue by eslynunez** [aws-quickstart/saas-identity-cognito#17]
Hey yall, 
I just want to say thanks for providing this quick start it has made alot of our development much faster.

I am running into an issue where an order manager in my user pool makes a request to an endpoint that the user should not have a role to access. I would expect an unauthorized error response but instead it triggers a ~503~ 502 (sorry) if a user does not have permissions for the role. Is this expected behavior? 

Thanks

**Comment by eslynunez** [comment]
Here's some additional information.

The 502 manifests itself as an issue in the dynamodb-helper here are the cloudwatch logs from the request.
```
debug: Fetching all tenants
error: Unable to create table: Tenant
/app/shared-modules/dynamodb-helper/node_modules/aws-sdk/lib/request.js:31
throw err;
^
TypeError: Cannot read property 'scan' of undefined
at DynamoDBHelper.<anonymous> (/app/shared-modules/dynamodb-helper/dynamodb-helper.js:141:18)
at DynamoDBHelper.<anonymous> (/app/shared-modules/dynamodb-helper/dynamodb-helper.js:286:21)
at DynamoDBHelper.<anonymous> (/app/shared-modules/dynamodb-helper/dynamodb-helper.js:186:20)
at Request.<anonymous> (/app/shared-modules/dynamodb-helper/node_modules/aws-sdk/lib/request.js:364:18)
at Request.callListeners (/app/shared-modules/dynamodb-helper/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/app/shared-modules/dynamodb-helper/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/app/shared-modules/dynamodb-helper/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/app/shared-modules/dynamodb-helper/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/app/shared-modules/dynamodb-helper/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /app/shared-modules/dynamodb-helper/node_modules/aws-sdk/lib/state_machine.js:26:10
```
I believe the issue may be stemmed from here? 
https://github.com/aws-quickstart/saas-identity-cognito/blob/ae6d347687d6a50855e1457c0df3400c08b2c381/app/source/shared-modules/dynamodb-helper/dynamodb-helper.js#L294

in the getDynamoDBDocumentClient callback the first parameter returned is the docClient instance but the callback function expects (error, docClient) as the usage below and througout indicates

https://github.com/aws-quickstart/saas-identity-cognito/blob/ae6d347687d6a50855e1457c0df3400c08b2c381/app/source/shared-modules/dynamodb-helper/dynamodb-helper.js#L140

I'll be happy to submit a PR if this is an issue.  

Note: this was not the original issue but it is something that came up while trying to understand the issue I was having above. I believe this is what is causing the 502 error to appear but it does not answer my question on user role isolation. 

I hope y'all have a nice day.

**Comment by judahb** [comment]
@eslynunez I am not aware of this issue. Thanks for bringing it to my attention. Did you test the code change before you completed the pull request? If so, I will test your code, validate, and potentially merge. (This may take some time given other work priorities)

**Comment by eslynunez** [comment]
Unfortunately, I did not. My team has partially moved away the dynamo helper from the quick start. With shifted priorities I'm not sure I can devote enough time to this. I submitted this in hopes that It may help someone else. I'll be sure to follow the issue.

**Comment by judahb** [comment]
@eslynunez It will be challenging to prioritize testing, and implementing your pull request if you were unable to test it at all prior to submitting. Given you are not devoting time to this and your priorities have shifted, this will need to be looked at with lower priority.

**Comment by eslynunez** [comment]
understood, thank you for providing the quick start it has been very educational to our saas efforts.  have a nice day.
