### ISSUE TITLE
How to integrate this github repository changes with the CodePipeline - part of this quickstart?

### ISSUE THREAD

**Issue by alexephesoft** [aws-quickstart/saas-identity-cognito#20]
How do you integrate the GitHub repository changes with the CodePipeline - part of this QuickStart? 

When changes in the service Nodejs code take place, I manually zip it, upload it to the S3 bucket for the service and from this point on, the CodePiple - installed by the saas-cognito quickstart - picks up and everything gets build correctly according to the installed script.  The only piece for CI/CD is connector between GitHub and Amazon S3 Bucket. 

I understand that it is possible to connect GitHub with S3 Bucket in CodePipeline but this connector works on the Git branch level only and not on a folder of the branch level that I need. I want to avoid keeping each service in its individual git branch or use Jenkins for connection. Any suggestions? How did you do it?

**Comment by judahb** [comment]
Hi @alexephesoft, If i understand your question, it appears to be a feature request for CodePipeline. If that is the case, this is not the place to request this. I would recommend you reach out to AWS Support and submit a ticket so its formally tracked and where the service team can prioritize internally.
