### ISSUE TITLE
How to add federal identities to this Quickstart saas.

### ISSUE THREAD

**Issue by pvkadam** [aws-quickstart/saas-identity-cognito#21]
Hi, 

 I know there is like a lot of resources in S3 that has been created due to Quickstart in aws. Now I need federated identities login in my website, how do I get it ? As usually, federated identities are set up in user pools in cognito, but here the Quickstart is creating new user pools for every user sign up. Hence could you help me with this question "where and what should I configure to get federated identities in the  website

**Comment by judahb** [comment]
@pvkadam I apologize however I am not sure i understand your question. Can you please rephrase and specify your use case? For each Tenant that is created a User Pool and Cognito Federated Identity is Created, so this question is confusing and requires some clarity as to what you are trying to achieve.

**Comment by pvkadam** [comment]
It would be really helpful if you could reply sooner.
As far as I know, I can configure the federated identities in USER Pools, but the Quickstart application is creating more user pools everytime a new user signsup.
So where or what should I configure to get those federated identities enabled for my website ?

**Comment by judahb** [comment]
This is not a support channel, AWS support tickets can be submitted via the AWS console. This QuickStart has been architected for One User Pool and One Federated Identity per Tenant. Issues or Enhancements with QuickStart do not have an SLA assigned.
