### ISSUE TITLE
Federated/ social login to Quickstart saas 

### ISSUE THREAD

**Issue by pvkadam** [aws-quickstart/saas-identity-cognito#22]
It would be really helpful if you could reply sooner.
As far as I know, I can configure the federated identities in USER Pools, but the Quickstart application is creating more user pools everytime a new user signs-up.
So where or what should I configure to get those federated identities/ social login enabled for my website ?

**Comment by judahb** [comment]
If you are in need of AWS support, please log a support ticket in the AWS console. If you are interested in an enhancement or their is an issue with the QuickStart than Github is the appropriate place.

**Comment by judahb** [comment]
We are not a support channel. We will focus on bugs or enhancements. For support, please reach out to AWS Support.
