### ISSUE TITLE
all endpoints failing

### ISSUE THREAD

**Issue by f0rever-johnson** [aws-quickstart/saas-identity-cognito#23]
I am receiving a "Endpoint request timed out error" for every api call i make through postman. All the health check apis are working tho.  Is it not possible to call the api endpoint directly?

**Comment by judahb** [comment]
This is insufficient information to troubleshoot. You must provide the logs, use case, api call. and more information and details for us to assist.

**Comment by f0rever-johnson** [comment]
As of right now, I am simply trying to reverse engineer this project. Figure out how the calls are made, where the calls get made to.  Using postman to call api gateway, i get the error "Endpoint request timed out error".  When I log into cognito, there is a new user pool & associated federated identity but now user associated with it.   I am looking for logs created in cloudwatch, but I am not seeing any errors.  
![screen shot 2018-09-21 at 4 17 14 pm](https://user-images.githubusercontent.com/21150708/45904069-e007b100-bdb9-11e8-81bd-4df306209913.png)
<img width="1680" alt="screen shot 2018-09-21 at 4 17 02 pm" src="https://user-images.githubusercontent.com/21150708/45904070-e007b100-bdb9-11e8-8bea-8c035c5fd6a6.png">
<img width="1678" alt="screen shot 2018-09-21 at 4 16 12 pm" src="https://user-images.githubusercontent.com/21150708/45904071-e007b100-bdb9-11e8-864c-f4f9c666ac6f.png">
