### ISSUE TITLE
How to implement Client certificate authentication?

### ISSUE THREAD

**Issue by dan-lind** [aws-quickstart/saas-identity-cognito#24]
Towards the end of the deployment guide, there is a section for "Considerations for Production Environments" where the first point says "Client certificates – For full security, we recommend that you use client certificates for authentication." 
But no more details about this. 

How would one go about implementing a solution using client certificates that integrates somehow with Cognito?

**Comment by judahb** [comment]
Client Certificates are simply a way of ensuring that you must go through an API Gateway to access the Application behind the Application Load Balancer. This is done programmatically. The certs are typically maintained in the Certificates section of the API Gateway and you would implement the code in the microservice to ensure that certificate was present to verify the client requests were initiated from the API Gateway. See more information here https://docs.aws.amazon.com/apigateway/latest/developerguide/getting-started-client-side-ssl-authentication.html
