### ISSUE TITLE
Is this suppose to be limited to a set of the created user pools?

### ISSUE THREAD

**Issue by imduffy15** [aws-quickstart/saas-identity-cognito#27]
Hi All,

It is my assumption that the validation function should only consider a JWT generated by one of the user pools created during tenant registration as a valid one and not just any JWT.

I'm a little confused by the validation code provided in the custom authorizer as at a quick glance it appears to be validating any valid JWT.

## The JWK is being fetched based of the ISS in the token

Should this be getting fetched dynamically like this? I would have guessed that the verifier is loaded with a set of trusted JWKs.

It being dynamically fetched makes me think any valid JWT will pass validation successfully.

https://github.com/aws-quickstart/saas-identity-cognito/blob/master/functions/source/custom-authorizer/index.js#L44-L81

## Locking this down to a specific user pool

The following if condition https://github.com/aws-quickstart/saas-identity-cognito/blob/master/functions/source/custom-authorizer/index.js#L144

```
    if (decodedJwt.payload.iss != iss) {
        console.log("invalid issuer");
        context.fail("invalid issuer");
        return;
    }
```

looks suspicious, as just a few lines up, iss is defined https://github.com/aws-quickstart/saas-identity-cognito/blob/master/functions/source/custom-authorizer/index.js#L132 as follows:

```
    var iss = decodedJwt.payload.iss;
```

As such, the condition will always be true and the issuer will never be invalid. Is this the expected functionality? I would have thought there is a whitelist of allowed user pool ids somewhere.

**Comment by judahb** [comment]
@imduffy15 1) Yes, In relationship to the first part, this should be limited to specific user pools. I would recommend you migrate to the newer version of the API Gateway Blueprint https://github.com/awslabs/aws-apigateway-lambda-authorizer-blueprints/tree/master/blueprints/nodejs and adjust to lookup based on multiple user pools and this should assist. ( will assess the priority and potentially complete a pull request to automate this. The question here is the appropriate approach to automate this. There are a number of ways to do this, and ultimately if their are a large number of user pools and the authorizer needs to be performant a DB lookup might not be the best approach. How would you recommend introducing this? (potentially a JSON document that gets updated that gets serialized as an array?) 2) For the second item called out, I will analyze and respond accordingly when i have time.

**Comment by judahb** [comment]
opening a new enhancement request and closing this

**Comment by judahb** [comment]
https://github.com/aws-quickstart/saas-identity-cognito/issues/28
