### ISSUE TITLE
Remembering Authentication Token

### ISSUE THREAD

**Issue by derektumulak** [aws-quickstart/saas-identity-cognito#29]
I've deployed the latest version of this quickstart and when I refresh after logging in or navigate away and back the site requires me to re-authenticate. Is there a solution for this?

Thanks,
-Derek

**Comment by judahb** [comment]
This is a simple change, but one that is not scoped in this version of this quickstart or client. I would recommend a local storage key for the authorization/JWT token. This would retain as long as you don't clear your cache. I would have /logout clear that token, or a refresh take place.
