### ISSUE TITLE
Custom scopes per tenant

### ISSUE THREAD

**Issue by andrey-moor** [aws-quickstart/saas-identity-cognito#3]
How can I define custom resource server scopes per tenant (based on tenant plan)? Is that possible with one user pool?

**Comment by judahb** [comment]
Hi Andrey, In order to provide the required architecture guidance, I need some clarity. Are you trying to provide functionality based on the tenant "tier", or "usage plan." If so, are you defining "tier" as a custom attribute within the Cognito User Pool?

**Comment by andrey-moor** [comment]
@judahb yes - I'm trying to provide functionality based on tenant tier. But I also want to have certain custom scopes per tenant tier. As far as I understand I can define custom scopes per user pool and not per user group for example.

**Comment by judahb** [comment]
You can define scopes per User Pool and Not Per Group. That being said, a Group ends up as a claim within the JWT. See this blog post as an example.
https://aws.amazon.com/blogs/apn/managing-saas-identity-through-custom-attributes-and-amazon-cognito/

**Comment by andrey-moor** [comment]
Exactly - so it doesn't matter which tenant tier the user belongs to - he will also get all of the custom scopes for user pool. Is there anything I'm missing?

**Comment by judahb** [comment]
The custom claims will be there, however they will be null. That being said, you can create an application ID which states which claims can be read and by whom. So if their is an application ID per Tenant, this will make this claims invisible. This seems like a product management question, and I would recommend you reach out to the Cognito forum to engage an Amazon Cognito Developer or Product Manager.
