### ISSUE TITLE
Passing temporary credentials to lambda functions

### ISSUE THREAD

**Issue by suhaig** [aws-quickstart/saas-identity-cognito#31]
Hi,

we're evaluating Saas on AWS, but instead of using Node.js Express applications on EC2 we're using lambda functions. In the Quickstart every Node.js application (like product-manager or order-manager) is passing the HTTP request to the token-manager to get temporary AWS credentials. We're thinking about implementing temporary credentials retrieval in the custom lambda authorizer and passing those credentials (accessKey, secretKey and sessionToken) to our lambda functions. So the lambda functions know nothing about JWT tokens and web identity.
Do you think it's a good idea? What are the drawbacks of this solution? Is it acceptable from a security standpoint?

Thank you,
Gábor

**Comment by judahb** [comment]
@suhaig I have seen this done before by other clients, through the Lambda Context object. Their are a couple potential security risks here, as well as scalability/performance concerns. I am not advising against this completely, but here are some of the design considerations to think about. I would recommend discussing with your solutions architect at AWS one on one.

1) The longevity of STS creds !== the longevity of the JWT Token, so how did you streamline the token renewal or invalidation process. 
2) When passing credentials from a Lambda Function to an API Gateway, are these being encrypted in-transit and how are you passing them to the lambda function?
3) Typically we advise against passing these credentials unless they are going directly to an AWS secure and managed endpoint, and a custom API Gateway managed by you does not constitute a managed AWS endpoint as you maintain the security through the shared security model, not us.

What about caching these in a Reddis elasticache cluster for hot read of these creds with server side encryption and or persisting within AWS Secrets Manager/Parameter Store with KMS? You can associate the STS credentials with a JWT as the Hash/Key as it constitutes a unique value and map that to the corresponding STS creds.

**Comment by suhaig** [comment]
Thanks for you thorough answer @judahb.

When the user hits our API GW we validate her token in our custom lambda authorizer and get tenant scoped temporary credentials from Cognito/STS. We put these credentials into the context object (`authResponse.context`) and let API GW call the lambda function that implements the endpoint functionality. The lambda - for example - get some object from S3 with the temporary credentials and that's it, we don't use those credentials again. The next time the user hits our API GW we ask for temporary credentials again. As far as I understand the Quickstart works the same way, asks for temporary credentials for every HTTP request. However, in the case of the Quickstart the credentials don't travel from the API GW to the Node.js applications.

Regarding token longevity, if the user hits API GW with a valid token Cognito/STS will give us temporary credentials. Should we care about if the token expires while the lambda is running?

We have another use case (processing S3 uploads asynchronously and getting temporary credentials for the uploader), I can write about that if you are interested.

Regards,
Gábor

**Comment by judahb** [comment]
Hey Gábor, I am not completely sure I understand your question. The Lambda function should verify the expiry, and you may include custom logic to ensure it has sufficient time to validate before expiry. Example, if the token expires in 5 seconds respond back with an Unauthorized error. Not sure that answers your question though. As far as doing the Credential Configuration on Lambda Function, I would ensure you have adequate security best practices and encryption for any Security credentials you create. As this is a demo environment we did not do that, but its recommended to ensure all Access/Secrets are only accessed by those permitted to do so. Storing them un-encrypted in a database or a cache is likely a security risk.

**Comment by juancpgo** [comment]
@judahb I also want to cache AWS Credentials on a serverless (Lambda) architecture, so I'm very interested in your suggestion.

You said:
> caching these in a Reddis elasticache cluster for hot read of these creds with server side encryption and or persisting within AWS Secrets Manager/Parameter Store with KMS

In my case, I'm targeting thousands of customers. So if I have 10,000 tenants storing their temporary (1h) AWS credentials with **Secrets Manager** or **SSM Parameter** Store seems quite expensive, since it's charged per secret/parameter. It would cost hundreds if not thousands monthly.

But **Redis ElastiCache** on the other hand seems very cost effective at this scale: a cluster "cache.t3.micro" cluster costs $0.017 per hour ($12.24/mo), and it can store 500 MB, which would fit 500,000 AWS credentials of 1 KB each, comfortably suiting this number of active tenants.

Is this 👆 reasoning correct?

And also, can you confirm that using **Redis ElastiCache** for caching temporary credentials will be a significant gain in performance, as opposed to requesting new AWS credentials for every single API request from the client?
