### ISSUE TITLE
SaaS Identity and Isolation with Amazon Cognito on the AWS Cloud

### ISSUE THREAD

**Issue by saydulk** [aws-quickstart/saas-identity-cognito#33]
deployment guide for SaaS Identity and Isolation with Amazon Cognito on the AWS Cloud is not clear and its not work 1st time attempt. is their any video at AWS Knowledge Center for SaaS Identity and Isolation with Amazon Cognito on the AWS Cloud?
![Screenshot from 2019-03-18 00-11-53](https://user-images.githubusercontent.com/1058663/54495880-7e607380-4912-11e9-9ceb-3b60e89bc2de.png)

**Comment by judahb** [comment]
No. Please submit a support ticket through AWS Support for any issues.
