### ISSUE TITLE
is it possible to server Alb DNS to HTTP instead of HTTP ? 

### ISSUE THREAD

**Issue by nikhilkapoorephesoft** [aws-quickstart/saas-identity-cognito#37]
Hi,

I am new to AWS can anyone suggest me how can I make my ALB DNS URL from **http:**//loadbalancer.region.aws.com to **https**//loadbalancer.region.aws.com and
also is it possible to stop DDOS attack on load balancer URL?

**Comment by judahb** [comment]
Please reach out to support. You would need to configure a Certificate and an HTTPS listener with that Certificate. Not in scope for this demo.
