### ISSUE TITLE
Question: creating policies via IAM

### ISSUE THREAD

**Issue by jinseo-jang** [aws-quickstart/saas-identity-cognito#39]
Hi,
Page 24 of the PDF file(SaaS Identity and Isolation with Amazon Cognito) says _6. Tenant registration provisions policies for each tenant role._ 
Also Figure13 in the same page shows like that.

But I couldn't find the code related code in _app/source/tenant-registration/src/server.js_
does the code locate in the User Management Service, not Tenant Registration Service?
I would like to know where it is in.

**Comment by brtrvn** [comment]
Jinseo - both the tenant and system registration services are orchestrating services that delegate user creation to the user service. You'll see, for example, in the tenant registration service that POST to /reg will make a POST to /reg in the user service. The actual calls to IAM to create the polices, roles and attachments is in the helper code cognito-user.js in the user-manager source tree.

**Comment by brtrvn** [comment]
Feel free to reach out again if you have more questions. Closing this for now.
