### ISSUE TITLE
Custom s3 bucket

### ISSUE THREAD

**Issue by hffmnn** [aws-quickstart/saas-identity-cognito#42]
Not sure where to put this (I guess all quickstart example which use `QSS3BucketName` and `QSS3KeyPrefix` might have this problem:

The template URLs get substituted like this: 
```
!Sub https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}templates/copy-files.template
```
but my custom s3 bucket URL looks like this:

```
https://${QSS3BucketName}.s3-eu-west-1.amazonaws.com/${QSS3KeyPrefix}/templates/copy-files.template
```
The difference in the template is `s3` vs `s3-eu-west-1`. Or is there an option to create a s3 bucket with a custom URL?

Any ideas?

**Comment by davmayd** [comment]
This was resolved by the introduction of the QSS3BucketRegion parameter (commit: https://github.com/aws-quickstart/saas-identity-cognito/commit/a389032952751dc17bebce3adad6995979567732)
