### ISSUE TITLE
Deployment fails: Update node.js runtime to 12

### ISSUE THREAD

**Issue by asimSiddiquiSeer** [aws-quickstart/saas-identity-cognito#43]
Trying to deploy this quickstart, results in an error.

The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 97b91157-e14c-4aad-89b4-bd7b9781d6e8)

**Comment by DragonpunkAdmin** [comment]
I'm getting this issue as well, and can confirm it's the same as the other gentleman's ECS/API issue.

**Comment by davmayd** [comment]
The node.js runtime has been updated and the deployment is completing successfully
