### ISSUE TITLE
[Security] ALB is public reachable

### ISSUE THREAD

**Issue by hffmnn** [aws-quickstart/saas-identity-cognito#50]
The ALB is reachable via a public (http) url. This makes hiding everything behind API GW useless, because a malicious user, that finds out the public url, could circumvent things like throttling, API Keys...

To reproduce:
After successful deployment open the API GW console and copy e.g. the Endpoint Url of `/auth`. This url is reachable via e.g. `curl -d '{"userName":"<userName>", "password":"1234"}' -H 'Content-Type: application/json' <authServiceBaseUrl>/auth`

**Comment by brtrvn** [comment]
Thanks for your comment. At the time this sample code was created, Amazon API Gateway did not support private VPC integrations (see https://aws.amazon.com/about-aws/whats-new/2017/11/amazon-api-gateway-supports-endpoint-integrations-with-private-vpcs/).

Today you could modify the solution to use a VPCLink to the ALB fronting the ECS Services and keep those private inside your VPC.
