### ISSUE TITLE
QuickStart not sending email to system user.

### ISSUE THREAD

**Issue by ltrevino** [aws-quickstart/saas-identity-cognito#53]
I have deployed the stack and no email is sent to the email for the system user.

-I read logs but nothing is wrong or error.
-I changed the region.
-I changed the email several times to different domains.
-I registered the email in SES.

Could you tell me if something is missing in the guide or if it is an issue.

Thanks.

**Comment by jaychandran** [comment]
Yes, I was also facing the same issue and didn't find any errors in the logs.  Another issue I noticed was getting CORS error when trying to register a new user via the UI. Sorry, I don't have the CORS error as I deleted the stack from my account.

**Comment by davmayd** [comment]
This was fixed by PR #54 and is confirmed resolved
