### ISSUE TITLE
User with same email in more than one tenant

### ISSUE THREAD

**Issue by davidwhand** [aws-quickstart/saas-identity-cognito#7]
Judah,

Can a user be with the same email be in more than one tenant?  If so, how does the user "know" what tenant they are logging into?  I am assuming email is the userid.  Do we just handle something like that in the application layer?  User would just select or provide the tenant?

David

**Comment by judahb** [comment]
The application is tracking the emails/usernames in the Users table. This is how we are preventing overlapping email addresses for multiple user pools. This is handled in application layer when using multiple user pools, however if you want to do a single user pool with multiple groups, where a collection of groups are specified for tenant, than Cognito can do this for you. As an example, you can have three groups for one tenant, such as Tenant1-Marketing, Tenant1-Finance, and Tenant1-IT, each of these with a different IAM Role assigned. This is not how we architected this quick start, but this may be preferred in specific scenarios. Its use case specific, however in this other model Cognito when using one User Pool will prevent duplicate ID's with a configuration you specify in the Cognito SDK or Control Panel.
