### ISSUE TITLE
Angular 5 upgrade and a RDBMS example.

### ISSUE THREAD

**Issue by swapnil0545** [aws-quickstart/saas-identity-cognito#9]
Hi,

Can we expect an upgrade to the example in future with angular and using a mysql or sql-server for db.

The project on which I am working on will be using this architecture, we will be using these 2 things.
I would have contributed but its not an open source, but will see if I make any loosely coupled modules that I can share. But currently using rdbms instead of dynamodb will be a challenge.

Thanks for the efforts.

**Comment by judahb** [comment]
Angular 5, MySQL, and SQL-Server are not currently in-scope for this specific quick-start. We have potential plans to create content around other database options, however SQL and RDMS designs are generally covered at a Database Per Tenant, or Schema Per Tenant. Some potential options are recommended in the following white paper. https://d0.awsstatic.com/whitepapers/Multi_Tenant_SaaS_Storage_Strategies.pdf
